<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Tink</AssemblyName>
    <Version>0.1.0</Version>
    <Description>tink data-flow node frame protocol (universal, language-agnostic)</Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Tink.fs" />
    <Compile Include="test_tink.fs" />
  </ItemGroup>

</Project>